### ISSUE TITLE
-countdown mode of 30-300s has seemingly arbitrary 90+ hours added to the timer

### ISSUE THREAD

**Issue by git-3847** [dylex/xdaliclock#1]
The title pretty much says it all.  I *think* I fixed it up with the attached patch.
[countdown-mode-work.patch.txt](https://github.com/dylex/xdaliclock/files/10613974/countdown-mode-work.patch.txt)

Thanks for maintaining this code base!

**Comment by dylex** [comment]
Thanks.  I was going to say you should report this upstream to jwz but it looks like it is only a problem with my hex time patches, so I've applied it here.  I'm not sure I ever tried countdown mode with hex so I can't actually say for sure it works.
